BEGIN
   FOR t IN (SELECT table_name FROM all_tables WHERE owner = 'GC_ADMIN') LOOP
      EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, DELETE, ALTER ON GC_ADMIN.' || t.table_name || ' TO BACKEND';
      -- EXECUTE IMMEDIATE 'CREATE SYNONYM BACKEND.' || t.table_name || ' FOR GC_ADMIN.' || t.table_name;
   END LOOP;
END;

CREATE OR REPLACE TRIGGER set_default_schema_for_Backend
AFTER LOGON ON BACKEND.SCHEMA
BEGIN
   EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = GC_ADMIN';
END;

GRANT SELECT ANY DICTIONARY TO BACKEND;